#!/bin/bash

# TODO write usage
usage() {
cat << EOF
Usage:
$0 --gdx-dir <dir> --project-dir <dir> --name <project name> --package <com.example.project> --class <ApplicationListener> --sdk-dir <android sdk dir>

Options:
	--class
		Main application class file

	--gdx-dir
		Where libgdx is located.

	--name
		Name of the project

	--package
		Package of the project

	--project-dir
		Base location of project directories, i.e. where all
		Project, Project-desktop, Project-android directories
		are located.

	--sdk-dir
		Location of the android sdk

	-h, --help
		Displays this text
EOF
}

# Parse the arguments
while [ -n "$*" ]; do
	case $1 in
	-h)
		usage
		exit 1
		;;
	--help)
		usage
		exit 1
		;;
	--gdx-dir)
		shift
		GDX_DIR="$1"
		;;
	--class)
		shift
		CLASS="$1"
		;;
	--name)
		shift
		NAME="$1"
		;;
	--package)
		shift
		PACKAGE="$1"
		;;
	--project-dir)
		shift
		PROJECT_DIR="$1"
		;;
	--sdk-dir)
		shift
		SDK_DIR="$1"
		;;

	esac

	shift
done


if [ "$GDX_DIR" = "" ]; then
	echo "No gdx-dir set!"
	usage
	exit
elif [ "$CLASS" = "" ]; then
	echo "No class set!"
	usage
	exit
elif [ "$NAME" = "" ]; then
	echo "No name set!"
	usage
	exit
elif [ "$PACKAGE" = "" ]; then
	echo "No package set!"
	usage
	exit
elif [ "$PROJECT_DIR" = "" ]; then
	echo "No project dir set!"
	usage
	exit
elif [ "$SDK_DIR" = "" ]; then
	echo "No Android SDK dir set!"
	usage
	exit
fi


#Program
OLD_PWD=$PWD
cd "$GDX_DIR"
cd "dist"
java -jar gdx-setup.jar --dir "$PROJECT_DIR" --name "$NAME" --package "$PACKAGE" --mainClass "$CLASS" --sdkLocation "$SDK_DIR"
cd "$OLD_PWD"
