#!/bin/bash

EXTENSIONS=("gdx-box2d" "gdx-bullet")

usage() {
cat << EOF
Usage:
$0 --gdx-dir <dir> --project-dir <dir> --name <project name> --package <com.example.project> --class <ApplicationListener> --sdk-dir <android sdk dir>

Options:
	--class
		Main application class file

	--gdx-dir
		Where libgdx is located.

	--name
		Name of the project

	--project-dir
		Base location of project directories, i.e. where all
		Project, Project-desktop, Project-android directories
		are located.

	-h, --help
		Displays this text
EOF
}

# Parse the arguments
while [ -n "$*" ]; do
	case $1 in
	-h)
		usage
		exit 1
		;;
	--help)
		usage
		exit 1
		;;
	--gdx-dir)
		shift
		GDX_DIR="$1"
		;;
	--name)
		shift
		NAME="$1"
		;;
	--project-dir)
		shift
		PROJECT_DIR="$1"
		;;
	esac

	shift
done


if [ "$GDX_DIR" = "" ]; then
	echo "No gdx-dir set!"
	usage
	exit
elif [ "$NAME" = "" ]; then
	echo "No name set!"
	usage
	exit
elif [ "$PROJECT_DIR" = "" ]; then
	echo "No project dir set!"
	usage
	exit
fi

# Create extension string
for extension in ${EXTENSIONS[@]}; do
	EXTENSIONS_STRING="$EXTENSIONS_STRING $extension"
done

# Build
OLD_PWD=$PWD
cd "$GDX_DIR"
ant clean
ant gdx-backend-android gdx-backend-lwjgl gdx-box2d gdx-bullet gdx-core gdx-jnigen $EXTENSIONS_STRING
cd "dist"

# Main project
MAIN_DIR_LIBS="$PROJECT_DIR/$NAME/libs"
cp -v gdx.jar "$MAIN_DIR_LIBS"
cp -v sources/gdx-sources.jar "$MAIN_DIR_LIBS"

# Extensions for the main program
for extension in ${EXTENSIONS[@]}; do
	cp -v "extensions/$extension/${extension}.jar" "$MAIN_DIR_LIBS"
	cp -v "extensions/$extension/sources/${extension}-sources.jar" "$MAIN_DIR_LIBS"
done

# Android
ANDROID_DIR_LIBS="$PROJECT_DIR/$NAME-android/libs"
cp -v gdx-backend-android.jar "$ANDROID_DIR_LIBS"
cp -v sources/gdx-backend-android-sources.jar "$ANDROID_DIR_LIBS"

# Desktop
DESKTOP_DIR_LIBS="$PROJECT_DIR/$NAME-desktop/libs"
cp -v gdx-backend-lwjgl-natives.jar "$DESKTOP_DIR_LIBS"
cp -v gdx-backend-lwjgl.jar "$DESKTOP_DIR_LIBS"
cp -v sources/gdx-backend-lwjgl-sources.jar "$DESKTOP_DIR_LIBS"

cd "$OLD_PWD"
