#!/bin/bash

POSSIBLE_ARGS=('appengine' 'game')

APPENGINE_TASKS=(
	'deployAppengineRelease'
	'deployAppengineBeta'
	'deployAppengineNightly'
	'deployAppengineDev'
)

GAME_TASKS=(
	'deployGameNightlyDev'
	'deployGameNightlyRelease'
	'deployGameBeta'
)

tasks=()



# Parse arguments
while [ -n "$*" ]; do
	case $1 in
	appengine)
		tasks+=("${APPENGINE_TASKS[@]}")
		;;
	game)
		tasks+=("${GAME_TASKS[@]}")
		;;
	esac
	shift
done

# No arguments sync all
if [ ${#tasks[@]} -eq 0 ]; then
	tasks=( "${GAME_TASKS[@]}")
	tasks+=( "${APPENGINE_TASKS[@]}")
fi

# Run tasks
for task in ${tasks[@]}; do
	./gradlew $task

	if [ $? -ne 0 ]; then
		break
	fi

	sleep 3
done
# ./gradlew setAppengineBeta && ./gradlew server:appengineUpdate && ./gradlew setAppengineNightly && ./gradlew server: && ./gradlew deployAppengineBeta && ./gradlew deployNightlyDev && ./gradlew deployNightlyRelease && ./gradlew deployBeta
