#!/bin/bash

POSSIBLE_ARGS=('appengine' 'game')

APPENGINE_TASKS=(
	'setAppengineBeta'
	'server:appengineUpdate'
	'setAppengineNightly'
	'server:appengineUpdate'
	'setAppengineDev'
	'server:appengineUpdate'
)

GAME_TASKS=(
	'deployNightlyDev'
	'deployNightlyRelease'
	'deployBeta'
)

tasks=()



# Parse arguments
while [ -n "$*" ]; do
	case $1 in
	appengine)
		tasks+=("${APPENGINE_TASKS[@]}")
		;;
	game)
		tasks+=("${GAME_TASKS[@]}")
		;;
	esac
	shift
done

# No arguments sync all
if [ ${#tasks[@]} -eq 0 ]; then
	tasks=( "${APPENGINE_TASKS[@]}")
	tasks+=( "${GAME_TASKS[@]}")
fi

# Run tasks
for task in ${tasks[@]}; do
	./gradlew $task

	if [ $? -ne 0 ]; then
		break
	fi

	sleep 3
done
# ./gradlew setAppengineBeta && ./gradlew server:appengineUpdate && ./gradlew setAppengineNightly && ./gradlew server: && ./gradlew deployAppengineBeta && ./gradlew deployNightlyDev && ./gradlew deployNightlyRelease && ./gradlew deployBeta
